name: Deploy Astro Project to Deno Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # Para poder clonar el repositorio

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 2.2.4

      - name: Install dependencies
        run: deno install

      - name: Build project
        run: deno task build

      - name: Install deployctl
        run: deno install -gArf jsr:@deno/deployctl

      - name: Deploy to Deno Deploy
        run: deployctl deploy --project=jhosscy-blogdeepres-29 --env=DENO_DEPLOY_TOKEN=ddp_kWJLs8X1qauwNiyr2nr3F7zaCQ4U3H24eB61 ./dist/server/entry.mjs
